// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TerritoryTool.ServerSide.Persistence;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(TerritoryToolDbContext))]
    [Migration("20250527093959_PersonEnabled")]
    partial class PersonEnabled
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.ActionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTimeUtc")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DateTimeUTC");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Successful")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ActionLog");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.AspNetRoleClaims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.AspNetRoles", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.AspNetUserClaims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.AspNetUserLogins", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.AspNetUserRoles", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.AspNetUserTokens", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.AspNetUsers", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LockoutEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Person");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.Territory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("MapUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("MapUrl")
                        .IsUnique();

                    b.HasIndex("PersonId");

                    b.ToTable("Territory");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GivenBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GivenDateUtc")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsAutomaticGivenDate")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool?>("IsAutomaticPickedDate")
                        .HasColumnType("BOOLEAN");

                    b.Property<int>("PersonId")
                        .HasColumnType("INT");

                    b.Property<string>("PickedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PickedDateUtc")
                        .HasColumnType("DATETIME")
                        .HasColumnName("PickedDateUTC");

                    b.Property<int>("TerritoryId")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("GivenBy");

                    b.HasIndex("PersonId");

                    b.HasIndex("PickedBy");

                    b.HasIndex("TerritoryId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.ActionLog", b =>
                {
                    b.HasOne("TerritoryTool.ServerSide.Persistence.Entities.AspNetUsers", "User")
                        .WithMany("ActionLog")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.AspNetRoleClaims", b =>
                {
                    b.HasOne("TerritoryTool.ServerSide.Persistence.Entities.AspNetRoles", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.AspNetUserClaims", b =>
                {
                    b.HasOne("TerritoryTool.ServerSide.Persistence.Entities.AspNetUsers", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.AspNetUserLogins", b =>
                {
                    b.HasOne("TerritoryTool.ServerSide.Persistence.Entities.AspNetUsers", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.AspNetUserRoles", b =>
                {
                    b.HasOne("TerritoryTool.ServerSide.Persistence.Entities.AspNetRoles", "Role")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerritoryTool.ServerSide.Persistence.Entities.AspNetUsers", "User")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.AspNetUserTokens", b =>
                {
                    b.HasOne("TerritoryTool.ServerSide.Persistence.Entities.AspNetUsers", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.Territory", b =>
                {
                    b.HasOne("TerritoryTool.ServerSide.Persistence.Entities.Person", "Person")
                        .WithMany("TerritoriesInUse")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.Transaction", b =>
                {
                    b.HasOne("TerritoryTool.ServerSide.Persistence.Entities.AspNetUsers", "GivenByNavigation")
                        .WithMany("TransactionGivenByNavigation")
                        .HasForeignKey("GivenBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerritoryTool.ServerSide.Persistence.Entities.Person", "Person")
                        .WithMany("Transactions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerritoryTool.ServerSide.Persistence.Entities.AspNetUsers", "PickedByNavigation")
                        .WithMany("TransactionPickedByNavigation")
                        .HasForeignKey("PickedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TerritoryTool.ServerSide.Persistence.Entities.Territory", "Territory")
                        .WithMany("Transactions")
                        .HasForeignKey("TerritoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GivenByNavigation");

                    b.Navigation("Person");

                    b.Navigation("PickedByNavigation");

                    b.Navigation("Territory");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.AspNetRoles", b =>
                {
                    b.Navigation("AspNetRoleClaims");

                    b.Navigation("AspNetUserRoles");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.AspNetUsers", b =>
                {
                    b.Navigation("ActionLog");

                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserRoles");

                    b.Navigation("AspNetUserTokens");

                    b.Navigation("TransactionGivenByNavigation");

                    b.Navigation("TransactionPickedByNavigation");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.Person", b =>
                {
                    b.Navigation("TerritoriesInUse");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TerritoryTool.ServerSide.Persistence.Entities.Territory", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
