set check_function_bodies = off;

create extension if not exists citext with schema extensions;
create extension if not exists pg_trgm with schema extensions;
create extension if not exists unaccent with schema extensions;
create extension if not exists pgtap with schema extensions;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'app_role') then
    create type public.app_role as enum ('SUPERADMIN', 'ADMIN', 'USER');
  end if;
end $$;

create or replace function public.immutable_unaccent(value text)
returns text
language sql
immutable
parallel safe
set search_path = public, extensions
as $$
  select extensions.unaccent(value)
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username extensions.citext not null unique,
  auth_email extensions.citext not null unique,
  role public.app_role not null default 'USER',
  must_change_password boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.persons (
  id integer generated by default as identity primary key,
  name text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint persons_name_not_blank check (length(btrim(name)) > 0)
);

create unique index if not exists persons_name_unique_ci
  on public.persons (lower(name));

create index if not exists persons_name_trgm_idx
  on public.persons using gin ((public.immutable_unaccent(lower(name))) extensions.gin_trgm_ops);

create table if not exists public.territories (
  id integer generated by default as identity primary key,
  code extensions.citext not null unique,
  name text not null,
  map_url text not null unique,
  image_path text,
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint territories_code_not_blank check (length(btrim(code::text)) > 0),
  constraint territories_name_not_blank check (length(btrim(name)) > 0),
  constraint territories_map_url_not_blank check (length(btrim(map_url)) > 0)
);

create unique index if not exists territories_name_unique_ci
  on public.territories (lower(name));

create index if not exists territories_name_trgm_idx
  on public.territories using gin ((public.immutable_unaccent(lower(name))) extensions.gin_trgm_ops);

create index if not exists territories_code_trgm_idx
  on public.territories using gin ((public.immutable_unaccent(lower(code::text))) extensions.gin_trgm_ops);

create table if not exists public.territory_transactions (
  id integer generated by default as identity primary key,
  territory_id integer not null references public.territories(id) on delete cascade,
  person_id integer not null references public.persons(id) on delete restrict,
  given_by uuid not null references public.profiles(id) on delete restrict,
  given_at timestamptz not null,
  is_automatic_given_date boolean not null default true,
  picked_by uuid references public.profiles(id) on delete restrict,
  picked_at timestamptz,
  is_automatic_picked_date boolean,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint picked_requires_user check (picked_at is null or picked_by is not null) not valid,
  constraint picked_auto_requires_picked_at check (
    (picked_at is null and is_automatic_picked_date is null)
    or (picked_at is not null and is_automatic_picked_date is not null)
  ) not valid,
  constraint picked_after_given check (picked_at is null or picked_at >= given_at) not valid
);

create unique index if not exists territory_transactions_one_open_per_territory
  on public.territory_transactions (territory_id)
  where picked_at is null;

create index if not exists territory_transactions_territory_given_idx
  on public.territory_transactions (territory_id, given_at desc);

create index if not exists territory_transactions_recent_idx
  on public.territory_transactions (given_at desc, picked_at desc);

create index if not exists territory_transactions_person_id_idx
  on public.territory_transactions (person_id);

create index if not exists territory_transactions_given_by_idx
  on public.territory_transactions (given_by);

create index if not exists territory_transactions_picked_by_idx
  on public.territory_transactions (picked_by);

create table if not exists public.action_logs (
  id integer generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete restrict,
  action_type integer not null,
  message text not null,
  successful boolean not null,
  created_at timestamptz not null default now()
);

create index if not exists action_logs_created_idx
  on public.action_logs (created_at desc);

create index if not exists action_logs_user_idx
  on public.action_logs (user_id);

create table if not exists public.migration_user_map (
  old_aspnet_id text primary key,
  new_auth_id uuid not null unique references auth.users(id) on delete cascade
);

comment on table public.migration_user_map is 'Temporary mapping used by SQLite -> Supabase import scripts. Remove after migration validation if not needed.';

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
  before update on public.profiles
  for each row execute function public.touch_updated_at();

drop trigger if exists persons_touch_updated_at on public.persons;
create trigger persons_touch_updated_at
  before update on public.persons
  for each row execute function public.touch_updated_at();

drop trigger if exists territories_touch_updated_at on public.territories;
create trigger territories_touch_updated_at
  before update on public.territories
  for each row execute function public.touch_updated_at();

drop trigger if exists territory_transactions_touch_updated_at on public.territory_transactions;
create trigger territory_transactions_touch_updated_at
  before update on public.territory_transactions
  for each row execute function public.touch_updated_at();

create or replace function public.current_app_role()
returns public.app_role
language sql
stable
security invoker
set search_path = public
as $$
  select role from public.profiles where id = (select auth.uid())
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select coalesce(public.current_app_role() in ('SUPERADMIN', 'ADMIN'), false)
$$;

create or replace function public.is_superadmin()
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select coalesce(public.current_app_role() = 'SUPERADMIN', false)
$$;

create or replace function public.require_authenticated()
returns uuid
language plpgsql
stable
security invoker
set search_path = public
as $$
declare
  v_user_id uuid := (select auth.uid());
begin
  if v_user_id is null then
    raise exception 'UNAUTHENTICATED' using errcode = '28000';
  end if;

  return v_user_id;
end;
$$;

create or replace function public.require_admin()
returns uuid
language plpgsql
stable
security invoker
set search_path = public
as $$
declare
  v_user_id uuid := public.require_authenticated();
begin
  if not public.is_admin() then
    raise exception 'FORBIDDEN' using errcode = '42501';
  end if;

  return v_user_id;
end;
$$;

create or replace function public.require_superadmin()
returns uuid
language plpgsql
stable
security invoker
set search_path = public
as $$
declare
  v_user_id uuid := public.require_authenticated();
begin
  if not public.is_superadmin() then
    raise exception 'FORBIDDEN' using errcode = '42501';
  end if;

  return v_user_id;
end;
$$;

create or replace function public.add_action_log(
  p_action_type integer,
  p_message text,
  p_user_id uuid,
  p_successful boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_user_id is null then
    raise exception 'UNAUTHENTICATED' using errcode = '28000';
  end if;

  insert into public.action_logs (user_id, action_type, message, successful)
  values (p_user_id, p_action_type, p_message, p_successful);
end;
$$;

create or replace view public.territory_current_state
with (security_invoker = true)
as
select
  t.id,
  t.code,
  t.name,
  t.map_url,
  t.image_path,
  t.archived,
  open_tx.id as active_transaction_id,
  open_tx.person_id,
  p.name as person_name,
  open_tx.given_at,
  last_picked.last_picked_at
from public.territories t
left join public.territory_transactions open_tx
  on open_tx.territory_id = t.id
 and open_tx.picked_at is null
left join public.persons p
  on p.id = open_tx.person_id
left join lateral (
  select max(tt.picked_at) as last_picked_at
  from public.territory_transactions tt
  where tt.territory_id = t.id
) last_picked on true;

create or replace view public.territory_details
with (security_invoker = true)
as
select
  t.id as territory_id,
  t.code,
  t.name,
  t.map_url,
  t.image_path,
  t.archived,
  tt.id as transaction_id,
  tt.person_id,
  p.name as person_name,
  tt.given_at,
  tt.is_automatic_given_date,
  tt.picked_at,
  tt.is_automatic_picked_date,
  given.username as given_by_username,
  picked.username as picked_by_username
from public.territories t
left join public.territory_transactions tt on tt.territory_id = t.id
left join public.persons p on p.id = tt.person_id
left join public.profiles given on given.id = tt.given_by
left join public.profiles picked on picked.id = tt.picked_by;

create or replace view public.recent_transactions
with (security_invoker = true)
as
select
  tt.id as transaction_id,
  tt.territory_id,
  t.name as territory_name,
  t.code as territory_code,
  tt.person_id,
  p.name as person_name,
  tt.given_at,
  tt.is_automatic_given_date,
  tt.picked_at,
  tt.is_automatic_picked_date,
  given.username as given_by_username,
  picked.username as picked_by_username
from public.territory_transactions tt
join public.territories t on t.id = tt.territory_id
join public.persons p on p.id = tt.person_id
join public.profiles given on given.id = tt.given_by
left join public.profiles picked on picked.id = tt.picked_by
where tt.given_at >= now() - interval '3 days'
   or tt.picked_at >= now() - interval '3 days';

alter table public.profiles enable row level security;
alter table public.persons enable row level security;
alter table public.territories enable row level security;
alter table public.territory_transactions enable row level security;
alter table public.action_logs enable row level security;
alter table public.migration_user_map enable row level security;

drop policy if exists "profiles self read" on public.profiles;
create policy "profiles self read"
on public.profiles for select
to authenticated
using ((select auth.uid()) = id or public.is_admin());

drop policy if exists "profiles self update password flag" on public.profiles;
create policy "profiles self update password flag"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id and role = (select role from public.profiles p where p.id = (select auth.uid())));

drop policy if exists "persons authenticated read" on public.persons;
create policy "persons authenticated read"
on public.persons for select
to authenticated
using (enabled or public.is_admin());

drop policy if exists "territories authenticated read" on public.territories;
create policy "territories authenticated read"
on public.territories for select
to authenticated
using (not archived or public.is_admin());

drop policy if exists "transactions authenticated read" on public.territory_transactions;
create policy "transactions authenticated read"
on public.territory_transactions for select
to authenticated
using (true);

drop policy if exists "action logs superadmin read" on public.action_logs;
create policy "action logs superadmin read"
on public.action_logs for select
to authenticated
using (public.is_superadmin());

drop policy if exists "migration map no client access" on public.migration_user_map;
create policy "migration map no client access"
on public.migration_user_map for all
to authenticated
using (false)
with check (false);

create or replace function public.give_territory(
  territory_code text,
  person_name text,
  custom_date timestamptz default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := public.require_authenticated();
  v_territory public.territories%rowtype;
  v_person public.persons%rowtype;
  v_given_at timestamptz := coalesce(custom_date, now());
  v_last_picked_at timestamptz;
begin
  if custom_date is not null and custom_date > now() + interval '1 day' then
    raise exception 'INVALID_DATE' using errcode = '22007';
  end if;

  select * into v_territory
  from public.territories
  where code = territory_code::extensions.citext
    and archived = false
  for update;

  if not found then
    raise exception 'TERRITORY_NOT_FOUND' using errcode = 'P0002';
  end if;

  if exists (
    select 1 from public.territory_transactions
    where territory_id = v_territory.id and picked_at is null
  ) then
    raise exception 'TERRITORY_ALREADY_IN_USE' using errcode = '23505';
  end if;

  select * into v_person
  from public.persons
  where lower(name) = lower(person_name)
    and enabled = true;

  if not found then
    raise exception 'PERSON_NOT_FOUND' using errcode = 'P0002';
  end if;

  select max(picked_at) into v_last_picked_at
  from public.territory_transactions
  where territory_id = v_territory.id;

  if v_last_picked_at is not null and v_given_at < v_last_picked_at then
    raise exception 'GIVEN_DATE_BEFORE_LAST_PICKED_DATE' using errcode = '22007';
  end if;

  insert into public.territory_transactions (
    territory_id,
    person_id,
    given_by,
    given_at,
    is_automatic_given_date
  )
  values (
    v_territory.id,
    v_person.id,
    v_user_id,
    v_given_at,
    custom_date is null
  );

  perform public.add_action_log(
    11,
    format('Given territory (%s) %s to %s. IsCustomDate: %s', v_territory.code, v_territory.name, v_person.name, custom_date is not null),
    v_user_id,
    true
  );
end;
$$;

create or replace function public.pick_territory(
  territory_code text,
  custom_date timestamptz default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := public.require_authenticated();
  v_territory public.territories%rowtype;
  v_transaction public.territory_transactions%rowtype;
  v_picked_at timestamptz := coalesce(custom_date, now());
begin
  select * into v_territory
  from public.territories
  where code = territory_code::extensions.citext
    and archived = false
  for update;

  if not found then
    raise exception 'TERRITORY_NOT_FOUND' using errcode = 'P0002';
  end if;

  select * into v_transaction
  from public.territory_transactions
  where territory_id = v_territory.id
    and picked_at is null
  for update;

  if not found then
    raise exception 'TERRITORY_NOT_IN_USE' using errcode = 'P0002';
  end if;

  if v_picked_at < v_transaction.given_at then
    raise exception 'PICKED_DATE_BEFORE_GIVEN_DATE' using errcode = '22007';
  end if;

  update public.territory_transactions
  set picked_by = v_user_id,
      picked_at = v_picked_at,
      is_automatic_picked_date = custom_date is null
  where id = v_transaction.id;

  perform public.add_action_log(
    12,
    format('Picked territory (%s) %s. IsCustomDate: %s', v_territory.code, v_territory.name, custom_date is not null),
    v_user_id,
    true
  );
end;
$$;

create or replace function public.update_transaction(
  transaction_id integer,
  person_id integer,
  given_at timestamptz,
  picked_at timestamptz default null
)
returns public.territory_transactions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := public.require_admin();
  v_existing public.territory_transactions%rowtype;
  v_result public.territory_transactions%rowtype;
begin
  if picked_at is not null and picked_at < given_at then
    raise exception 'INVALID_DATES' using errcode = '22007';
  end if;

  if not exists (select 1 from public.persons p where p.id = update_transaction.person_id and p.enabled = true) then
    raise exception 'PERSON_NOT_FOUND' using errcode = 'P0002';
  end if;

  select * into v_existing
  from public.territory_transactions tt
  where tt.id = update_transaction.transaction_id
  for update;

  if not found then
    raise exception 'TRANSACTION_NOT_FOUND' using errcode = 'P0002';
  end if;

  if picked_at is null and exists (
    select 1
    from public.territory_transactions tt
    where tt.territory_id = v_existing.territory_id
      and tt.picked_at is null
      and tt.id <> update_transaction.transaction_id
  ) then
    raise exception 'TERRITORY_ALREADY_IN_USE' using errcode = '23505';
  end if;

  update public.territory_transactions tt
  set person_id = update_transaction.person_id,
      given_at = update_transaction.given_at,
      picked_at = update_transaction.picked_at,
      picked_by = case when update_transaction.picked_at is null then null else coalesce(tt.picked_by, v_user_id) end,
      is_automatic_picked_date = case when update_transaction.picked_at is null then null else coalesce(tt.is_automatic_picked_date, false) end
  where tt.id = update_transaction.transaction_id
  returning * into v_result;

  perform public.add_action_log(
    14,
    format('Transaction %s updated', transaction_id),
    v_user_id,
    true
  );

  return v_result;
end;
$$;

create or replace function public.delete_transaction(transaction_id integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := public.require_admin();
  v_existing public.territory_transactions%rowtype;
begin
  select * into v_existing
  from public.territory_transactions
  where id = transaction_id
  for update;

  if not found then
    raise exception 'TRANSACTION_NOT_FOUND' using errcode = 'P0002';
  end if;

  delete from public.territory_transactions where id = transaction_id;

  perform public.add_action_log(
    15,
    format('Transaction %s deleted', transaction_id),
    v_user_id,
    true
  );
end;
$$;

create or replace function public.add_person(name text)
returns public.persons
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := public.require_admin();
  v_result public.persons%rowtype;
begin
  if name is null or btrim(name) = '' then
    raise exception 'INVALID_PARAMETERS' using errcode = '22023';
  end if;

  insert into public.persons (name)
  values (btrim(name))
  returning * into v_result;

  perform public.add_action_log(8, format('Person %s added', v_result.name), v_user_id, true);
  return v_result;
exception
  when unique_violation then
    raise exception 'PERSON_ALREADY_EXISTS' using errcode = '23505';
end;
$$;

create or replace function public.update_person(
  person_id integer,
  name text,
  enabled boolean
)
returns public.persons
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := public.require_admin();
  v_existing public.persons%rowtype;
  v_result public.persons%rowtype;
begin
  if name is null or btrim(name) = '' or enabled is null then
    raise exception 'INVALID_PARAMETERS' using errcode = '22023';
  end if;

  select * into v_existing from public.persons where id = person_id for update;
  if not found then
    raise exception 'PERSON_NOT_FOUND' using errcode = 'P0002';
  end if;

  update public.persons
  set name = btrim(update_person.name),
      enabled = update_person.enabled
  where id = person_id
  returning * into v_result;

  perform public.add_action_log(
    9,
    format('Person %s updated to %s. Enabled: %s', v_existing.name, v_result.name, v_result.enabled),
    v_user_id,
    true
  );

  return v_result;
exception
  when unique_violation then
    raise exception 'PERSON_ALREADY_EXISTS' using errcode = '23505';
end;
$$;

create or replace function public.delete_person(name text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := public.require_admin();
  v_person public.persons%rowtype;
begin
  select * into v_person from public.persons where lower(persons.name) = lower(delete_person.name) for update;
  if not found then
    raise exception 'PERSON_NOT_FOUND' using errcode = 'P0002';
  end if;

  if exists (select 1 from public.territory_transactions where person_id = v_person.id) then
    update public.persons set enabled = false where id = v_person.id;
  else
    delete from public.persons where id = v_person.id;
  end if;

  perform public.add_action_log(10, format('Deleting person %s', v_person.name), v_user_id, true);
end;
$$;

create or replace function public.add_territory(
  code text,
  name text,
  map_url text
)
returns public.territories
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := public.require_admin();
  v_result public.territories%rowtype;
begin
  if code is null or btrim(code) = '' or name is null or btrim(name) = '' or map_url is null or btrim(map_url) = '' then
    raise exception 'INVALID_PARAMETERS' using errcode = '22023';
  end if;

  insert into public.territories (code, name, map_url)
  values (btrim(code), btrim(name), btrim(map_url))
  returning * into v_result;

  perform public.add_action_log(1, format('Added territory %s %s', v_result.code, v_result.name), v_user_id, true);
  return v_result;
exception
  when unique_violation then
    raise exception 'TERRITORY_ALREADY_EXISTS' using errcode = '23505';
end;
$$;

create or replace function public.update_territory(
  territory_id integer,
  code text,
  name text,
  map_url text
)
returns public.territories
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := public.require_admin();
  v_result public.territories%rowtype;
begin
  if code is null or btrim(code) = '' or name is null or btrim(name) = '' or map_url is null or btrim(map_url) = '' then
    raise exception 'INVALID_PARAMETERS' using errcode = '22023';
  end if;

  update public.territories
  set code = btrim(update_territory.code),
      name = btrim(update_territory.name),
      map_url = btrim(update_territory.map_url)
  where id = territory_id
  returning * into v_result;

  if not found then
    raise exception 'TERRITORY_NOT_FOUND' using errcode = 'P0002';
  end if;

  perform public.add_action_log(
    2,
    format('Edited territory ID %s to: Code (%s) Name (%s) MapURL (%s)', territory_id, v_result.code, v_result.name, v_result.map_url),
    v_user_id,
    true
  );

  return v_result;
exception
  when unique_violation then
    raise exception 'TERRITORY_ALREADY_EXISTS' using errcode = '23505';
end;
$$;

create or replace function public.delete_territory(territory_id integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := public.require_admin();
  v_territory public.territories%rowtype;
begin
  select * into v_territory from public.territories where id = territory_id for update;
  if not found then
    raise exception 'TERRITORY_NOT_FOUND' using errcode = 'P0002';
  end if;

  if exists (select 1 from public.territory_transactions where territory_id = v_territory.id) then
    update public.territories set archived = true where id = v_territory.id;
  else
    delete from public.territories where id = v_territory.id;
  end if;

  perform public.add_action_log(3, format('Deleted territory id %s', territory_id), v_user_id, true);
end;
$$;

create or replace function public.search_territories(
  term text default null,
  only_free boolean default false,
  only_given boolean default false,
  take integer default 2147483647
)
returns setof public.territory_current_state
language sql
stable
security invoker
set search_path = public, extensions
as $$
  select *
  from public.territory_current_state t
  where t.archived = false
    and (not only_free or t.person_id is null)
    and (not only_given or t.person_id is not null)
    and (
      term is null
      or btrim(term) = ''
      or public.immutable_unaccent(lower(t.name)) % public.immutable_unaccent(lower(term))
      or public.immutable_unaccent(lower(t.code::text)) % public.immutable_unaccent(lower(term))
      or public.immutable_unaccent(lower(t.name)) like '%' || public.immutable_unaccent(lower(term)) || '%'
      or public.immutable_unaccent(lower(t.code::text)) like '%' || public.immutable_unaccent(lower(term)) || '%'
    )
  order by
    case when term is null or btrim(term) = '' then 0 else greatest(
      similarity(public.immutable_unaccent(lower(t.name)), public.immutable_unaccent(lower(term))),
      similarity(public.immutable_unaccent(lower(t.code::text)), public.immutable_unaccent(lower(term)))
    ) end desc,
    t.name
  limit greatest(take, 0);
$$;

create or replace function public.search_persons(
  term text default null,
  take integer default 2147483647
)
returns setof public.persons
language sql
stable
security invoker
set search_path = public, extensions
as $$
  select p.*
  from public.persons p
  where p.enabled = true
    and (
      term is null
      or btrim(term) = ''
      or public.immutable_unaccent(lower(p.name)) % public.immutable_unaccent(lower(term))
      or public.immutable_unaccent(lower(p.name)) like '%' || public.immutable_unaccent(lower(term)) || '%'
    )
  order by
    case when term is null or btrim(term) = '' then 0 else similarity(public.immutable_unaccent(lower(p.name)), public.immutable_unaccent(lower(term))) end desc,
    p.name
  limit greatest(take, 0);
$$;

create or replace function public.get_give_suggestions(count integer default 3)
returns setof public.territory_current_state
language sql
stable
security invoker
set search_path = public
as $$
  select *
  from public.territory_current_state t
  where t.archived = false
    and t.person_id is null
  order by t.last_picked_at asc nulls first, t.id asc
  limit greatest(count, 0);
$$;

create or replace function public.get_territory_statistics(territory_id integer)
returns jsonb
language plpgsql
stable
security invoker
set search_path = public
as $$
declare
  v_exists boolean;
  v_total integer;
  v_usage_rank integer;
  v_usage_count integer;
  v_avg_holding numeric;
  v_unique_persons integer;
begin
  perform public.require_authenticated();

  select exists(select 1 from public.territories where id = territory_id) into v_exists;
  if not v_exists then
    raise exception 'TERRITORY_NOT_FOUND' using errcode = 'P0002';
  end if;

  select count(*) into v_total from public.territories where archived = false;

  with usage as (
    select
      t.id,
      count(tt.id) as usage_count,
      dense_rank() over (order by count(tt.id) desc) as usage_rank
    from public.territories t
    left join public.territory_transactions tt on tt.territory_id = t.id
    where t.archived = false
    group by t.id
  )
  select usage_rank, usage_count
  into v_usage_rank, v_usage_count
  from usage
  where id = territory_id;

  select avg(extract(epoch from (picked_at - given_at)) / 86400.0)
  into v_avg_holding
  from public.territory_transactions
  where territory_id = get_territory_statistics.territory_id
    and picked_at is not null;

  select count(distinct person_id)
  into v_unique_persons
  from public.territory_transactions
  where territory_id = get_territory_statistics.territory_id;

  return jsonb_build_object(
    'totalTerritories', v_total,
    'usageRank', coalesce(v_usage_rank, v_total),
    'usageCount', coalesce(v_usage_count, 0),
    'averageHoldingTime', v_avg_holding,
    'uniqueUsersCount', coalesce(v_unique_persons, 0),
    'isHighUsage', coalesce(v_usage_rank, v_total) <= greatest(1, ceil(v_total * 0.25)),
    'isLowUsage', coalesce(v_usage_rank, v_total) > ceil(v_total * 0.75)
  );
end;
$$;

create or replace function public.get_action_logs(
  page_number integer default 1,
  page_size integer default 20,
  sort_field text default 'DateUtc',
  sort_order text default 'desc'
)
returns jsonb
language plpgsql
stable
security invoker
set search_path = public
as $$
declare
  v_total integer;
  v_offset integer := greatest(page_number - 1, 0) * greatest(page_size, 1);
  v_data jsonb;
begin
  perform public.require_superadmin();

  select count(*) into v_total from public.action_logs;

  with rows as (
    select
      al.action_type as "actionType",
      al.created_at as "dateUtc",
      al.message as "message",
      p.username as "userName",
      al.successful as "successful"
    from public.action_logs al
    join public.profiles p on p.id = al.user_id
    order by
      case when sort_field = 'ActionType' and lower(sort_order) = 'asc' then al.action_type end asc,
      case when sort_field = 'ActionType' and lower(sort_order) <> 'asc' then al.action_type end desc,
      case when sort_field = 'UserName' and lower(sort_order) = 'asc' then p.username end asc,
      case when sort_field = 'UserName' and lower(sort_order) <> 'asc' then p.username end desc,
      case when sort_field = 'Message' and lower(sort_order) = 'asc' then al.message end asc,
      case when sort_field = 'Message' and lower(sort_order) <> 'asc' then al.message end desc,
      case when sort_field = 'Successful' and lower(sort_order) = 'asc' then al.successful end asc,
      case when sort_field = 'Successful' and lower(sort_order) <> 'asc' then al.successful end desc,
      case when lower(sort_order) = 'asc' then al.created_at end asc,
      case when lower(sort_order) <> 'asc' then al.created_at end desc
    limit greatest(page_size, 1)
    offset v_offset
  )
  select coalesce(jsonb_agg(to_jsonb(rows)), '[]'::jsonb)
  into v_data
  from rows;

  return jsonb_build_object(
    'data', v_data,
    'totalCount', v_total,
    'pageNumber', page_number,
    'pageSize', page_size
  );
end;
$$;

create or replace function public.reset_migration_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform setval(pg_get_serial_sequence('public.persons', 'id'), coalesce((select max(id) from public.persons), 1), true);
  perform setval(pg_get_serial_sequence('public.territories', 'id'), coalesce((select max(id) from public.territories), 1), true);
  perform setval(pg_get_serial_sequence('public.territory_transactions', 'id'), coalesce((select max(id) from public.territory_transactions), 1), true);
  perform setval(pg_get_serial_sequence('public.action_logs', 'id'), coalesce((select max(id) from public.action_logs), 1), true);
end;
$$;

create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_claims jsonb;
  v_role text;
  v_username text;
begin
  select p.role::text, p.username::text
  into v_role, v_username
  from public.profiles p
  where p.id = (event->>'user_id')::uuid;

  v_claims := event->'claims';

  if v_role is not null then
    v_claims := jsonb_set(v_claims, '{app_role}', to_jsonb(v_role));
  end if;

  if v_username is not null then
    v_claims := jsonb_set(v_claims, '{UserName}', to_jsonb(v_username));
  end if;

  return jsonb_set(event, '{claims}', v_claims);
end;
$$;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('territory-images', 'territory-images', false, 5242880, array['image/png', 'image/jpeg', 'image/webp'])
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "territory images authenticated read" on storage.objects;
create policy "territory images authenticated read"
on storage.objects for select
to authenticated
using (bucket_id = 'territory-images');

drop policy if exists "territory images admin write" on storage.objects;
create policy "territory images admin write"
on storage.objects for insert
to authenticated
with check (bucket_id = 'territory-images' and public.is_admin());

drop policy if exists "territory images admin update" on storage.objects;
create policy "territory images admin update"
on storage.objects for update
to authenticated
using (bucket_id = 'territory-images' and public.is_admin())
with check (bucket_id = 'territory-images' and public.is_admin());

drop policy if exists "territory images admin delete" on storage.objects;
create policy "territory images admin delete"
on storage.objects for delete
to authenticated
using (bucket_id = 'territory-images' and public.is_admin());

revoke all on function public.add_action_log(integer, text, uuid, boolean) from public;
revoke all on function public.give_territory(text, text, timestamptz) from public;
revoke all on function public.pick_territory(text, timestamptz) from public;
revoke all on function public.update_transaction(integer, integer, timestamptz, timestamptz) from public;
revoke all on function public.delete_transaction(integer) from public;
revoke all on function public.add_person(text) from public;
revoke all on function public.update_person(integer, text, boolean) from public;
revoke all on function public.delete_person(text) from public;
revoke all on function public.add_territory(text, text, text) from public;
revoke all on function public.update_territory(integer, text, text, text) from public;
revoke all on function public.delete_territory(integer) from public;
revoke all on function public.search_territories(text, boolean, boolean, integer) from public;
revoke all on function public.search_persons(text, integer) from public;
revoke all on function public.get_territory_statistics(integer) from public;
revoke all on function public.get_give_suggestions(integer) from public;
revoke all on function public.get_action_logs(integer, integer, text, text) from public;
revoke all on function public.custom_access_token_hook(jsonb) from public;
revoke all on function public.reset_migration_sequences() from public;

grant usage on schema public to authenticated;
grant usage on schema public to service_role;
grant select on public.profiles to authenticated;
grant select on public.persons to authenticated;
grant select on public.territories to authenticated;
grant select on public.territory_transactions to authenticated;
grant select on public.action_logs to authenticated;
grant select on public.territory_current_state to authenticated;
grant select on public.territory_details to authenticated;
grant select on public.recent_transactions to authenticated;

grant update (must_change_password, updated_at) on public.profiles to authenticated;
grant all on public.profiles to service_role;
grant all on public.persons to service_role;
grant all on public.territories to service_role;
grant all on public.territory_transactions to service_role;
grant all on public.action_logs to service_role;
grant all on public.migration_user_map to service_role;
grant usage, select, update on all sequences in schema public to service_role;

grant execute on function public.give_territory(text, text, timestamptz) to authenticated;
grant execute on function public.pick_territory(text, timestamptz) to authenticated;
grant execute on function public.update_transaction(integer, integer, timestamptz, timestamptz) to authenticated;
grant execute on function public.delete_transaction(integer) to authenticated;
grant execute on function public.add_person(text) to authenticated;
grant execute on function public.update_person(integer, text, boolean) to authenticated;
grant execute on function public.delete_person(text) to authenticated;
grant execute on function public.add_territory(text, text, text) to authenticated;
grant execute on function public.update_territory(integer, text, text, text) to authenticated;
grant execute on function public.delete_territory(integer) to authenticated;
grant execute on function public.search_territories(text, boolean, boolean, integer) to authenticated;
grant execute on function public.search_persons(text, integer) to authenticated;
grant execute on function public.get_territory_statistics(integer) to authenticated;
grant execute on function public.get_give_suggestions(integer) to authenticated;
grant execute on function public.get_action_logs(integer, integer, text, text) to authenticated;
grant execute on function public.add_action_log(integer, text, uuid, boolean) to service_role;
grant execute on function public.reset_migration_sequences() to service_role;

grant execute on function public.custom_access_token_hook(jsonb) to supabase_auth_admin;
grant select on public.profiles to supabase_auth_admin;
grant usage on schema public to supabase_auth_admin;
